import argparse
import re
import subprocess
from collections import defaultdict
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import urlopen

DEFAULT_OPS_HEADER = "https://raw.githubusercontent.com/ml-explore/mlx/main/mlx/ops.h"


def read_text(source: str) -> str:
    parsed = urlparse(source)
    if parsed.scheme in {"http", "https"}:
        try:
            with urlopen(source) as resp:
                return resp.read().decode("utf-8")
        except Exception as url_error:
            try:
                result = subprocess.run(
                    ["curl", "-fsSL", source],
                    check=True,
                    capture_output=True,
                    text=True,
                )
                return result.stdout
            except Exception as curl_error:
                raise RuntimeError(
                    "Could not download ops header. Pass --ops-header with a local file path. "
                    f"urlopen error: {url_error}; curl error: {curl_error}"
                ) from curl_error
    return Path(source).read_text(encoding="utf-8")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*", "", text)
    return text


def parse_mlx_ops(header_text: str) -> dict[str, list[str]]:
    body = strip_comments(header_text)
    declarations = re.findall(r"MLX_API\s+(.*?);", body, flags=re.S)
    ops: dict[str, list[str]] = defaultdict(list)

    for decl in declarations:
        normalized = " ".join(decl.split())
        lparen = normalized.find("(")
        if lparen == -1:
            continue

        prefix = normalized[:lparen].strip()
        name_match = re.search(r"([A-Za-z_]\w*)\s*$", prefix)
        if not name_match:
            continue

        name = name_match.group(1)
        ops[name].append(f"{normalized};")

    return dict(ops)


def parse_mil_markdown(path: Path) -> set[str]:
    names = set()
    if not path.exists():
        return names
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\| `([^`]+)` \|", line)
        if match:
            names.add(match.group(1))
    return names


def render_markdown(
    ops: dict[str, list[str]],
    header_source: str,
    mil_ops: set[str],
) -> str:
    op_names = sorted(ops)
    lines = [
        "# MLX Ops",
        "",
        f"Source: `{header_source}`",
        "",
        f"Total unique ops: **{len(op_names)}**",
        "",
        "| Op | Overloads in `ops.h` |",
        "| --- | ---: |",
    ]

    for name in op_names:
        lines.append(f"| `{name}` | {len(ops[name])} |")

    if mil_ops:
        overlap = sorted(set(op_names) & mil_ops)
        mlx_only = sorted(set(op_names) - mil_ops)
        mil_only = sorted(mil_ops - set(op_names))
        lines.extend(
            [
                "",
                "## MIL Overlap",
                "",
                f"- Shared names: **{len(overlap)}**",
                f"- MLX-only names: **{len(mlx_only)}**",
                f"- MIL-only names: **{len(mil_only)}**",
            ]
        )

    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Markdown list of MLX ops from mlx/ops.h."
    )
    parser.add_argument(
        "--ops-header",
        default=None,
        help="Path or URL to mlx/ops.h (default: local mlx_ops.h/mlx/ops.h if present, otherwise GitHub URL).",
    )
    parser.add_argument(
        "--mil-markdown",
        type=Path,
        default=Path("mil_ops.md"),
        help="Optional Markdown file generated by print_mil_ops.py for overlap stats.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("mlx_ops.md"),
        help="Path to write Markdown output.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Also print generated Markdown to stdout.",
    )
    return parser.parse_args()


def resolve_ops_header(user_value: str | None) -> str:
    if user_value:
        return user_value

    for local_path in (Path("mlx_ops.h"), Path("mlx/ops.h")):
        if local_path.exists():
            return str(local_path)
    return DEFAULT_OPS_HEADER


def main() -> None:
    args = parse_args()
    ops_header = resolve_ops_header(args.ops_header)
    header_text = read_text(ops_header)
    mlx_ops = parse_mlx_ops(header_text)
    mil_ops = parse_mil_markdown(args.mil_markdown)
    markdown = render_markdown(mlx_ops, ops_header, mil_ops)

    args.output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {len(mlx_ops)} MLX ops to {args.output}")
    if mil_ops:
        print(f"Compared against {len(mil_ops)} MIL ops from {args.mil_markdown}")
    if args.stdout:
        print(markdown, end="")


if __name__ == "__main__":
    main()
